### ISSUE TITLE
YAML file with all fields commented out will throw MismatchedInputException even if I have default values for all the fields

### ISSUE THREAD

**Issue by serandel** [FasterXML/jackson-dataformats-text#154]
A curious behaviour I've encountered adding Jackson to a Kotlin project...

I'm trying to deserialize a YAML file to a Kotlin data class

`data class Settings(val wireframe: Boolean = false)`

with the following code

```
mapper = ObjectMapper(YAMLFactory())
mapper.registerModule(KotlinModule()) 

val settings = settingsFileInputStream.use {
   mapper.readValue(it, Settings::class.java)
}
```

If the file content is

`wireframe: true`

it works.

But if I comment out the settings like this:

`#wireframe: true`

then I get the following exception:

`com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input`

I believed it was because default parameters in the data class weren't accepted, but no. To prove that, I modified the settings like this:

`data class Settings(val wireframe: Boolean = false, val foo: String = "bar")`

and I can deserialize from this file: 

```
#wireframe: true
foo: foobar
```

but I get the exception again if I use

```
#wireframe: true
#foo: foobar
```

Jackson version: 2.9.10 (latest stable, AFAIK)

**Comment by michaelhixson** [comment]
Here's how I worked around this issue in a Java project, in case it helps anyone.

## Workaround 1

If my YAML file would be empty except for comments, add a `{}` at the top level to prevent the mapper from blowing up.

```
# This is a comment.
# foo=bar

# This {} is necessary because everything else is commented out.
{}
```

This "worked" but felt bad.  I felt compelled to explain the `{}` in my example YAML config file with a comment, but I would have preferred to not distract the reader with that stuff at all.  I'm no longer using this approach.

## Workaround 2

Do a two-step deserialization (1) from YAML to `JsonNode` then (2) from `JsonNode` to an instance of my class.  If the `JsonNode` is empty, which it will be when the YAML file contains only comments and white space, return a default value.  Otherwise, ask the `ObjectMapper` to read the `JsonNode`.

```java
Path yamlFile = ...
YAMLMapper yamlYapper = new YAMLMapper();
JsonNode tree;
try (InputStream inputStream = Files.newInputStream(yamlFile)) {
  tree = yamlMapper.readTree(inputStream);
}

if (tree.isEmpty()) {
  return MyConfig.defaultConfig();
}

ObjectMapper objectMapper = new ObjectMapper();
return objectMapper.treeToValue(tree, MyConfig.class);
```

This is the approach that I'm using currently.

**Comment by cowtowncoder** [comment]
@michaelhixson Thank you for sharing this! This makes sense as Tree Model can read "no content" as `MissingNode`. There are 2 other similar approaches now that you mention this, either:

1. create parser from `YAMLFactory` (via `mapper.getFactory()`), check `if (parser.nextToken() == null) { // no content `
2. create `MappingIterator<MyConfig>` via `mapper.readerFor(MyConfig.class).readValues())`, and see if `if (hasNext()) { ... has value ... } else { ... no value create default ... } `

in fact (2) might be the cleanest version:

```
try (MappingIterator<MyConfig> iterator = mapper.readerFor(MyConfig.class)
    .readValues()) {
  if (!iterator.hasValue()) {
    return MyConfig.defaultConfig();
  }
  return iterator.nextValue();
}
```

**Comment by mikebell90** [comment]
@cowtowncoder This appears to be fixed in Jackson 2.18.3 - which I updated to from 2.18.2. This test below started failing for me ;) I assume this is WAD?

```
    // An empty manifest throws up on the Node
    @Test
    public void testEmptyManifest() throws Exception {
        assertThrows(MismatchedInputException.class, () -> {
            try (InputStream is = new ByteArrayInputStream(new byte[0])) {
                deserialize(is);
            }
        });
    }
   private Manifest deserialize(InputStream is) throws IOException {
        JsonNode node = mapper.readTree(is);
        return objectMapper.treeToValue(node, Manifest.class);
    }
```

**Comment by cowtowncoder** [comment]
@mikebell90 2.18.3 should have no changes over 2.18.2 or 2.18.1 -- but 2.18.1 did upgrade SnakeYAML to 2.3. That seems like the only YAML-specific change.

But as to failure: I _think_ it should work (if I read this right, considering `Manifest` def is missing).
Although as per my earlier comment, empty docs are tricky to properly represent.

What exception do you get?

**Comment by mikebell90** [comment]
@cowtowncoder well that's where I may have put my foot in my mouth ;) 

It's
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.opentable.credentials.synchronizer.manifests.Manifest]: missing type id property 'kind'
 at [Source: UNKNOWN; byte offset: #UNKNOWN]

	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2051)
```

Manifest is actually a complicated polymorphic beast, but here's the first part

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = As.EXISTING_PROPERTY, property = "kind")
@JsonSubTypes({
  @JsonSubTypes.Type(value= ImmutableServiceManifest.class, name = "service"),
  @JsonSubTypes.Type(value= ImmutableSharedManifest.class, name = "shared"),
  @JsonSubTypes.Type(value= ImmutableDatabaseManifest.class, name = "database"),
  @JsonSubTypes.Type(value= ImmutableDBManifest.class, name = "db"),
  @JsonSubTypes.Type(value= ImmutablePKIDatabaseManifest.class, name = "pki"),
  @JsonSubTypes.Type(value= ImmutablePolicyManifest.class, name = "policy"),
})
public interface Manifest {
    ManifestKind getKind(); (many more properties)
```

So on the one hand maybe unrellated to above, though it "looked" similar. OTOH, why would this stop throwing an exception going from 2.18.2 => 2.18.3 (snakeyaml is 2.3 for both in our dep tree)

**Comment by cowtowncoder** [comment]
Yeah, this exception would come from even regular "empty" Document since -- as message states, type id `kind` is not included. And there is no `defaultImpl` defined (if there was that type would be used).

As to 2.18.3 stopping failure... `jackson-databind` has 11 fixes so maybe one of these changed things; polymorphic handling f.ex is fully by databind:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.18.3

although none seems like immediately suspicious.

**Comment by cowtowncoder** [comment]
Fixed in:
 
* 2.21.0
* 3.0.3
