### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "<<" (class com.wasiqb.config.DeviceSetting), not marked as ignorable

### ISSUE THREAD

**Issue by WasiqB** [FasterXML/jackson-dataformats-text#171]
When I am using common blocks in Yaml and referencing it in different location in same Yaml, I get following Error message.

```bash
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "<<" (class com.wasiqb.config.DeviceSetting), not marked as ignorable (3 known properties: "host", "port", "path"])
 at [Source: (File); line: 8, column: 24] (through reference chain: com.wasiqb.config.Settings["devices"]->java.util.LinkedHashMap["android"]->com.wasiqb.config.DeviceSetting["<<"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at com.wasiqb.config.ConfigLoader.getSettings(ConfigLoader.java:18)
	at com.wasiqb.config.ConfigLoaderTest.testJackson(ConfigLoaderTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

**However, same Yaml file works fine when using SnakeYaml.**

The sample code to replicate the issue is at [this gist](https://gist.github.com/WasiqB/ea3813cd4449681fcb8a94573d17b31d).

**Comment by WasiqB** [comment]
@cowtowncoder , any ETA on this? I think I need to revert to SnakeYaml for time being.

**Comment by cowtowncoder** [comment]
No, haven't had time to look into and unless someone else has, will not have time.

**Comment by contradictioned** [comment]
Just adding to my previous comment:
When debugging that error, you see that Jackson uses SnakeYaml on a lower level as parser, and not as interpreter.

Right now, the BeanSerializer (and maybe even other serializers, I am not sure) gets an attribute named "<<" and tries to fit this into the newly constructed bean. Also, the BeanSerializer is agnostic of the actually used Parser. So I guess, the best place to implement this behaviour is to hook into com.fasterxml.jackson.dataformat.yaml.YAMLParser#nextToken and, if the next token would be a "<<"-attribute, then inline the referenced object there?

**Comment by cowtowncoder** [comment]
@contradictioned your analysis is correct, wrt it'd `BeanDeserializer`, not `BeanSerializer` (for reading). And I think you are right that this handling would need to be in `YAMLParser#nextToken()`.
