### ISSUE TITLE
readValue() for empty YAML returns null, not empty map

### ISSUE THREAD

**Issue by damianszczepanik** [FasterXML/jackson-dataformats-text#173]
When passing empty YAML file into `ObjectMapper.readValue()` then `null` is returned, not empty map.
Example:
https://github.com/damianszczepanik/silencio/blob/master/src/main/java/pl/szczepanik/silencio/processors/YAMLProcessor.java#L44
Input file:
https://github.com/damianszczepanik/silencio/blob/master/src/test/resources/yaml/empty.yaml

When passing empty JSON `{}` this returns empty map so I would except to have same for YAML

**Comment by cowtowncoder** [comment]
Case of `{ }` is little bit different, since that is explicit Object, whereas I am not even sure what empty content for YAML should be. But I can see how it could be interpreted as empty Document.
I wonder what SnakeYAML itself sees such content as.

But it is possible that existing Jackson YAML backend is handling it before. So I hope to look into this in near future to see what is going on.

**Comment by cowtowncoder** [comment]
I am not sure there is something to change here: empty Map or POJO would be serialized as

```yaml
--- {}
```

(or without document start indicator `---` if so configured)

and empty content is parsed by SnakeYAML so that there is Stream start, Stream end events, but no Document events to indicate existence of document.
So to me returning `null` seems like the right thing.

**Comment by damianszczepanik** [comment]
But then it should be consistent with JSON mapper which AFAIR is not

**Comment by cowtowncoder** [comment]
@damianszczepanik How so? Passing empty file to JSON will not give you equivalent of `{ }` but either exception (if trying to bind content into POJO), or `null` with streaming read using `JsonParser`.

**Comment by rehevkor5** [comment]
Appears to me it doesn't even give `null`, it throws an exception:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (StringReader); line: 1, column: 1]

	at com.fasterxml.jackson.databind@2.12.4/com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind@2.12.4/com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
	at com.fasterxml.jackson.databind@2.12.4/com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
	at com.fasterxml.jackson.databind@2.12.4/com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind@2.12.4/com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
	
...
```
Seems to me like an empty YAML should be valid.

**Comment by cowtowncoder** [comment]
@rehevkor5 this is unfortunately quite tricky an area; but I would strongly suggest that anyone who needs to produce empty documents makes sure that YAML document start/separator marker (`---`) is used.

**Comment by cowtowncoder** [comment]
Fixed by #154 -- enabled with `YAMLReadFeature.EMPTY_DOCUMENT_AS_EMPTY_OBJECT`.
