### ISSUE TITLE
Issue creating an instance of CsvMapper

### ISSUE THREAD

**Issue by pavanarya** [FasterXML/jackson-dataformats-text#24]
Hi when trying to create an instance of CsvMapper I am getting following issue

CsvMapper mapper = new CsvMapper();

Error:
`java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.dataformat.csv.CsvFactory
	at com.fasterxml.jackson.dataformat.csv.CsvMapper.<init>(CsvMapper.java:39)
	at com.bluetrack.report.services.LeadReportService.csvWriter(LeadReportService.java:154)
	at com.bluetrack.report.services.LeadReportService.generateScheduledLeadReport(LeadReportService.java:140)
	at com.bluetrack.report.services.LeadReportService$$FastClassBySpringCGLIB$$418c5dc5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.bluetrack.report.services.LeadReportService$$EnhancerBySpringCGLIB$$7c047677.generateScheduledLeadReport(<generated>)
	at com.bluetrackmedia.scheduledreporting.ReportGenerator.generateLeadReport(ReportGenerator.java:56)
	at com.bluetrackmedia.scheduledreporting.ReportGenerator.generateReport(ReportGenerator.java:42)
	at com.bluetrackmedia.scheduledreporting.ReportGenerator$$FastClassBySpringCGLIB$$72f6c360.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.bluetrackmedia.scheduledreporting.ReportGenerator$$EnhancerBySpringCGLIB$$7f6c3bb2.generateReport(<generated>)
	at com.bluetrackmedia.scheduledreporting.scheduledtask.checkForPendingScheduledReports(scheduledtask.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

My Pom.xml:
`<dependency>
	  <groupId>com.fasterxml.jackson.dataformat</groupId>
	  <artifactId>jackson-dataformat-csv</artifactId>
	  <version>2.8.8</version>
	</dependency>`

When I see maven dependencies, I am able to see all dependent jars of jackson.

Thanks,
Pavan

**Comment by cowtowncoder** [comment]
Exception definitely looks like some of dependant jars was missing: two main guesses would be `jackson-core` (most likely) or perhaps `jackson-annotations`. But not sure what more I can suggest here.
