### ISSUE TITLE
YAML anchor `UnresolvedForwardReference` with builder

### ISSUE THREAD

**Issue by almson** [FasterXML/jackson-dataformats-text#292]
YAML anchor resolution fails with UnresolvedForwardReference in the following code.

```
// Generated by delombok at Mon Oct 11 17:00:06 EEST 2021
package mypackage;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.annotation.SimpleObjectIdResolver;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import java.util.List;
import org.junit.jupiter.api.Test;

public class JacksonYamlTest {

    static class Container {
        @JsonProperty
        List<Base> list;
    }


    @JsonTypeInfo(use = Id.NAME)
    @JsonSubTypes({@Type(name = "Derived", value = Derived.class)})
    @JsonIdentityInfo(generator = ObjectIdGenerators.StringIdGenerator.class, resolver = SimpleObjectIdResolver.class)
    interface Base {
    }


    @JsonDeserialize(builder = Derived.DerivedBuilder.class)
    static class Derived implements Base {
        @JsonProperty
        String a;

        Derived(final String a) {
            this.a = a;
        }


        @JsonPOJOBuilder(withPrefix = "", buildMethodName = "build")
        public static class DerivedBuilder {
            private String a;

            DerivedBuilder() {
            }

            @JsonProperty
            public DerivedBuilder a(final String a) {
                this.a = a;
                return this;
            }

            public Derived build() {
                return new Derived(this.a);
            }
        }

        public static DerivedBuilder builder() {
            return new DerivedBuilder();
        }
    }

    @Test
    public void typedObjectIdTest() throws Exception {
        String yaml = "list:\n" + 
                "    - !Derived &id1\n" + 
                "        a: foo\n" + 
                "    - *id1";
        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        Container container = mapper.readValue(yaml, Container.class);
        System.out.println(((Derived) container.list.get(0)).a);
        System.out.println(((Derived) container.list.get(1)).a);
        
        var serialized = mapper.writeValueAsString (container);
        System.out.println (serialized);
    }
}
```

throws

```
com.fasterxml.jackson.databind.deser.UnresolvedForwardReference: 
Unresolved forward references for: 
 at [Source: (StringReader); line: 4, column: 11]Object id [id1] (for `com.syncwords.config.JacksonYamlTest$Base`) at [Source: (StringReader); line: 4, column: 11].
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.checkUnresolvedObjectId(DefaultDeserializationContext.java:171)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4595)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
```

Note that changing `interface Base` to `static class Base` resolves the problem, however I require an interface. Everything else works fine except using anchors.

**Comment by cowtowncoder** [comment]
Correct: the failing case is with interface, otherwise combination does work.

**Comment by cowtowncoder** [comment]
Fixed for 3.2.0
