### ISSUE TITLE
YAML Anchor, reference fails with simple example #123 -- INVALID

### ISSUE THREAD

**Issue by vitaliy-sk** [FasterXML/jackson-dataformats-text#296]
Issue #123 reproducible on 2.13.0

Code sample:

```java
package test;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

public class Test {

    static class ScratchModel {
        public StringHolder foo;
        public StringHolder boo;
    }

    @JsonIdentityInfo(generator = ObjectIdGenerators.None.class)
    static class StringHolder {
        public String value;

        @Override
        public String toString() {
            return value;
        }
    }

    public void testObjectIdUsingNative() throws Exception
    {
        final String YAML_CONTENT =
                "foo: &foo1\n" +
                        "  value: bar\n" +
                        "boo: *foo1\n";
        System.out.println(YAML_CONTENT);
        System.out.println("---");
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        ScratchModel result = om.readValue(YAML_CONTENT, ScratchModel.class);
        System.out.println(result);
    }

    public static void main(String[] args) throws Exception {
        new Test().testObjectIdUsingNative();
    }

}
```

Output: 

```
foo: &foo1
  value: bar
boo: *foo1

---
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `test.Test$StringHolder` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('foo1')
 at [Source: (StringReader); line: 3, column: 6] (through reference chain: test.Test$ScratchModel["boo"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at test.Test.testObjectIdUsingNative(Test.java:34)
	at test.Test.main(Test.java:39)
```

**Comment by robbytx** [comment]
FWIW I'm encountering a similar issue with Dropwizard's configuration YAML (using jackson 2.19.2, snakeyaml 2.4), which seems to parse the YAML to com.fasterxml.jackson.databind.JsonNode, and then convert that to io.dropwizard.core.Configuration.  

In debugging I can see that the SnakeYAML parser is returning a `MappingStartEvent` with the correct anchor name, which jackson-dataformat-yaml makes available via `JsonParser.getObjectId()`, but the JsonNodeDeserializer seems to ignore the object id altogether, so the anchor reference is completely lost, and the later `AliasEvent` that is emitted is converted to a simple VALUE_STRING token.  

I see references to object id in TokenBuffer and BeanDeserializer (and subclasses), so perhaps YAML anchors are only expected to work for bean classes, not JsonNodes.

**Comment by cowtowncoder** [comment]
These are wrong in example:

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
```

as those are for Jackson 2.x; 3.x uses `tool.jackson` ?
I assume this is just copy/paste error, and does not matter otherwise?

**Comment by cowtowncoder** [comment]
@robbytx Correct: If parsing into `JsonNode`, all Object Id info will be completely lost -- there is nothing to hold that metadata. So that cannot be made to work; ony POJO/Bean classes can.

**Comment by cowtowncoder** [comment]
Looks like `ObjectIdGenerators.None` won't work -- might work with `ObjectIdGenerators.StringIdGenerator`?
Failing test exists, at any rate.

**Comment by cowtowncoder** [comment]
Ok the actual problem is this:

```
@JsonIdentityInfo(generator = ObjectIdGenerators.None.class)
```

which should instead be

```
@JsonIdentityInfo(generator = ObjectIdGenerators.StringIdGenerator.class)
```

because `None` basically means "disable Object Id handling"

With that, this is dup of #123 which was fixed in 2.9.9.
