### ISSUE TITLE
jackson-dataformat-csv 2.13.0 error with jaxrs

### ISSUE THREAD

**Issue by geniusit** [FasterXML/jackson-dataformats-text#302]
Hello,

Im trying to add a custom MessageBodyProvider with Jax-rs.
Everything works well with : 

```xml
<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
            <version>2.12.6</version>
        </dependency>
```

but with : 

```xml
<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
            <version>2.13.0</version>
        </dependency>
```

I got the following error : 

```java
2022-01-05 14:42:30,278 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /ws/export failed, error id: c20c360e-86e3-4a06-ac1f-30e220363f65-1: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.csv.CsvFactory._createContentReference(Ljava/lang/Object;)Lcom/fasterxml/jackson/core/io/ContentReference;
        at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:357)
        at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:16)
        at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:690)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1043)
        at sncf.mobilite.groupehv.eqs.ws.ExportedEventMessageBodyWriter.writeTo(ExportedEventMessageBodyWriter.java:49)
        at sncf.mobilite.groupehv.eqs.ws.ExportedEventMessageBodyWriter.writeTo(ExportedEventMessageBodyWriter.java:20)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
        at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
        at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
        at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Here is my code : 

```java
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import java.util.ArrayList;
import java.util.List;

@Path("/hello")
public class MyResource {
    
    @GET
    @Path("/export")
    @Produces("text/csv")
    public List<TestExportEvent> export() {

        TestExportEvent t1 = TestExportEvent.builder().firstName("f1").lastName("l1").age(1).build();
        TestExportEvent t2 = TestExportEvent.builder().firstName("f2").lastName("l2").age(2).build();
        TestExportEvent t3 = TestExportEvent.builder().firstName("f3").lastName("l3").age(3).build();
        
        List<TestExportEvent> repository = new ArrayList<>();
        repository.add(t1);
        repository.add(t2);
        repository.add(t3);
        
        return repository;
    }
}

import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;

import javax.ws.rs.Produces;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.ext.MessageBodyWriter;
import javax.ws.rs.ext.Provider;
import java.io.IOException;
import java.io.OutputStream;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.util.List;

@Provider
@Produces("text/csv")
public class ExportedEventMessageBodyWriter implements MessageBodyWriter<List<TestExportEvent>> {

    @Override
    public boolean isWriteable(Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType) {
        boolean ret=List.class.isAssignableFrom(type);
        return ret;
    }

    @Override
    public long getSize(List<TestExportEvent> t, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType)
    {
        return 0;
    }

    @Override
    public void writeTo(List<TestExportEvent> o, Class<?> type, Type genericType,
                        Annotation[] annotations, MediaType mediaType,
                        MultivaluedMap<String, Object> httpHeaders,
                        OutputStream entityStream)
            throws IOException, WebApplicationException {

        CsvMapper mapper = new CsvMapper();

        CsvSchema schema = mapper.schemaFor(TestExportEvent.class).withHeader();

        mapper.writer(schema).writeValue(entityStream, o);
        
    }
}


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;


@Builder
@Getter
@AllArgsConstructor
@Setter
public class TestExportEvent {

    private final String firstName;
    private final String lastName;
    private final int age;
}


```

no jar conflict in my classpath as you can see : 

[INFO] my-groupId:my-artifactId:jar:my-version
[INFO] +- io.quarkus:quarkus-arc:jar:2.2.1.Final:compile
[INFO] |  +- io.quarkus.arc:arc:jar:2.2.1.Final:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] |  |  |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.4.2.Final:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:2.2.1.Final:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.2.1.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.2.1.Final:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.4.4:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.4.4:compile
[INFO] |  |  |     +- org.eclipse.microprofile.config:microprofile-config-api:jar:2.0:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-annotation:jar:1.6.0:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.6.0:compile
[INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.6.0:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-constraint:jar:1.6.0:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:1.6.0:compile
[INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:2.4.4:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.9:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.2.Final:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile
[INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:21.2.0:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
[INFO] |  |  \- io.quarkus:quarkus-bootstrap-runner:jar:2.2.1.Final:compile
[INFO] |  |     \- io.smallrye.common:smallrye-common-io:jar:1.6.0:compile
[INFO] |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.2:compile
[INFO] +- io.quarkus:quarkus-resteasy-mutiny:jar:2.2.1.Final:compile
[INFO] |  +- io.quarkus:quarkus-resteasy:jar:2.2.1.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-http:jar:2.2.1.Final:compile
[INFO] |  |  |  +- io.quarkus:quarkus-security-runtime-spi:jar:2.2.1.Final:compile
[INFO] |  |  |  +- io.quarkus:quarkus-vertx-http-dev-console-runtime-spi:jar:2.2.1.Final:compile
[INFO] |  |  |  +- io.quarkus.security:quarkus-security:jar:1.1.4.Final:compile
[INFO] |  |  |  +- io.quarkus:quarkus-vertx-core:jar:2.2.1.Final:compile
[INFO] |  |  |  |  +- io.quarkus:quarkus-netty:jar:2.2.1.Final:compile
[INFO] |  |  |  |  |  +- io.netty:netty-codec:jar:4.1.65.Final:compile
[INFO] |  |  |  |  |  +- io.netty:netty-codec-http:jar:4.1.65.Final:compile
[INFO] |  |  |  |  |  +- io.netty:netty-codec-http2:jar:4.1.65.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-handler:jar:4.1.65.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec-haproxy:jar:4.1.65.Final:compile
[INFO] |  |  |  |  |  +- io.netty:netty-buffer:jar:4.1.65.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-transport:jar:4.1.65.Final:compile
[INFO] |  |  |  |  \- io.vertx:vertx-core:jar:4.1.2:compile
[INFO] |  |  |  |     +- io.netty:netty-common:jar:4.1.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-handler-proxy:jar:4.1.65.Final:compile
[INFO] |  |  |  |     |  \- io.netty:netty-codec-socks:jar:4.1.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-resolver:jar:4.1.65.Final:compile
[INFO] |  |  |  |     \- io.netty:netty-resolver-dns:jar:4.1.65.Final:compile
[INFO] |  |  |  |        \- io.netty:netty-codec-dns:jar:4.1.65.Final:compile
[INFO] |  |  |  \- io.vertx:vertx-web:jar:4.1.2:compile
[INFO] |  |  |     +- io.vertx:vertx-web-common:jar:4.1.2:compile
[INFO] |  |  |     +- io.vertx:vertx-auth-common:jar:4.1.2:compile
[INFO] |  |  |     \- io.vertx:vertx-bridge-common:jar:4.1.2:compile
[INFO] |  |  \- io.quarkus:quarkus-resteasy-server-common:jar:2.2.1.Final:compile
[INFO] |  |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-mutiny-common:jar:2.2.1.Final:compile
[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:2.2.1.Final:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-core:jar:4.7.0.Final:compile
[INFO] |     |  |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] |     |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile
[INFO] |     |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] |     +- io.quarkus:quarkus-mutiny:jar:2.2.1.Final:compile
[INFO] |     |  +- io.smallrye.reactive:mutiny:jar:1.0.0:compile
[INFO] |     |  +- io.quarkus:quarkus-smallrye-context-propagation:jar:2.2.1.Final:compile
[INFO] |     |  |  \- io.smallrye:smallrye-context-propagation:jar:1.2.0:compile
[INFO] |     |  |     +- io.smallrye:smallrye-context-propagation-api:jar:1.2.0:compile
[INFO] |     |  |     \- io.smallrye:smallrye-context-propagation-storage:jar:1.2.0:compile
[INFO] |     |  \- io.smallrye.reactive:mutiny-smallrye-context-propagation:jar:1.0.0:compile
[INFO] |     +- org.jboss.resteasy:resteasy-client:jar:4.7.0.Final:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-client-api:jar:4.7.0.Final:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-core-spi:jar:4.7.0.Final:compile
[INFO] |     |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |     |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |     |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |     |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |     |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile
[INFO] |     |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |     \- io.quarkus:quarkus-apache-httpclient:jar:2.2.1.Final:compile
[INFO] |        \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.12:provided
[INFO] \- com.fasterxml.jackson.dataformat:jackson-dataformat-csv:jar:2.13.1:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.4:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.4:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.12.4:compile

Why does the 2.13.0 fail to work ?

**Comment by yawkat** [comment]
There is a version conflict, you're using jackson-databind 2.12.4 with jackson-dataformat-csv 2.13.1. You can't mix versions like this

**Comment by geniusit** [comment]
So you have to change it in the lib, right ?  jackson-databind is a transitive dependency of jackson-dataformat-csv

**Comment by yawkat** [comment]
The dependency of jackson-dataformat-csv 2.13 is jackson-databind 2.13, you're bringing in the 2.12 from elsewhere

**Comment by geniusit** [comment]
but i don't see it in my dependency:tree ...

**Comment by yawkat** [comment]
it says so in your log above:

[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.4:compile

**Comment by geniusit** [comment]
![image](https://user-images.githubusercontent.com/3659037/148238323-d7a280a7-ffb1-41f0-bf8e-2419f5e5a5c6.png)

**Comment by geniusit** [comment]
![image](https://user-images.githubusercontent.com/3659037/148238502-8a9db355-0af4-4d89-b96b-6a466b6f4741.png)

**Comment by yawkat** [comment]
You can see the diverging versions in your second screenshot

**Comment by geniusit** [comment]
that's the issue. 
why the 3 transitives dependencies for jackson-dataformat are in the 2.12.4:compile version instead of 2.13 ?

**Comment by yawkat** [comment]
i don't know, it's something in your build changing the version – my guess is quarkus. jackson-dataformat-csv 2.13.0 has the right dependency versions set: https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-csv/2.13.0

**Comment by geniusit** [comment]
The Jackson BOM is already defined in quarkus, so the version shouldn't be set when defining some jackson dependencies. Sorry for the confusion
