### ISSUE TITLE
Weird Runtime Error: java.lang.NoSuchFieldError: DEFAULT_READ_CAPABILITIES

### ISSUE THREAD

**Issue by BelleChou** [FasterXML/jackson-dataformats-text#305]
Hi,

I basically got the same error as this issue:https://github.com/FasterXML/jackson-dataformats-text/issues/236
I confirmed that I am using 
Jackson-annotations = 2.12.6;
Jackson-core = 2.12.6;
Jackson-databind = 2.12.6;
Jackson-dataformat-csv = 2.12.6;

```
    public <T> List<T> csvToPojo(final Class<T> clazz, final InputStream stream) {
        final CsvSchema bootstrapSchema = CsvSchema.emptySchema().withHeader().withNullValue("#N/A");
        try {
            final MappingIterator<T> iter = new CsvMapper()
                    .readerFor(clazz)
                    .with(bootstrapSchema)
                    .readValue(stream);
            return iter.readAll();
        } catch (final IOException e) {
            throw new RuntimeException(
                    String.format(
                            "Failure while converting CSV input stream to list of pojos of type '%s'. message= [%s]",
                            clazz, e.getMessage()));
        }
    }
```

```
java.lang.NoSuchFieldError: DEFAULT_READ_CAPABILITIES

	at com.fasterxml.jackson.dataformat.csv.CsvParser.<clinit>(CsvParser.java:187)
	at com.fasterxml.jackson.dataformat.csv.impl.CsvParserBootstrapper.constructParser(CsvParserBootstrapper.java:161)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory._createParser(CsvFactory.java:402)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:312)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:15)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1053)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1431)
	at com.amazon.contracogsauxiliaryinputeventdataingestion.util.CsvUtil.csvToPojo(CsvUtil.java:36)
	at com.amazon.contracogsauxiliaryinputeventdataingestion.util.CsvUtilTest.testCsvToPojo(CsvUtilTest.java:27)
```

**Comment by cowtowncoder** [comment]
What you have is an incompatible (old) version of `jackson-core` in your classpath somewhere.
Most likely actual jar, but I suppose sometimes repackaged non-shaded copies of classes may exist as well.
But basically version of `JsonParser` that does NOT have specified field: that field was added in Jackson 2.12.0.
