### ISSUE TITLE
`IllegalArgumentException` when attempting to decode invalid UTF-8 surrogate by SnakeYAML (oss-fuzz 50431)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#400]
(note: issue found by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50431)

Looks like there is an uncaught `IllegalArgumentException` for certain input; problem caught by Fuzzing.
Stack trace looks like

```
== Java Exception: java.lang.IllegalArgumentException: Not a valid Unicode code point: 0xE30EEE
	 at java.base/java.lang.Character.toChars(Character.java:9175)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1973)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1919)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1068)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1050)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:436)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251)
	 at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:214)
	 at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
	 at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:176)
	 at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:403)
```

I think SnakeYAML should catch the problem, re-throw -- content is invalid, but should not get through as IAE.

I created #401 for the test.

**Comment by asomov** [comment]
@cowtowncoder thank you for the info:
https://bitbucket.org/snakeyaml/snakeyaml/issues/576

**Comment by cowtowncoder** [comment]
@asomov Thanks! For some reason I seem to lack access to see it tho...

**Comment by asomov** [comment]
@cowtowncoder because of the spam attack I had to close the issue tracker. I hope I will open it soon

**Comment by cowtowncoder** [comment]
Still open but will be resolved by SnakeYAML release after 2.0 (likely `2.1`)

**Comment by asomov** [comment]
Hopefully 2.1 will be released in August 2023

**Comment by cowtowncoder** [comment]
Fixed via #426

**Comment by cowtowncoder** [comment]
@asomov With SnakeYAML 2.1, this was fixed for Jackson 2.x. But it looks like `snakeyaml-engine` 2.6 has the same issue?

**Comment by asomov** [comment]
@cowtowncoder I will try to release snakeyaml-engine this weekend to solve it

**Comment by cowtowncoder** [comment]
@asomov No super hurry, but when you do, it'd be great if you could add a note here so I can make matching change.

Thank you!

**Comment by asomov** [comment]
@cowtowncoder SnakeYAML Engine 2.7 Released:
https://central.sonatype.com/artifact/org.snakeyaml/snakeyaml-engine/2.7/versions

**Comment by cowtowncoder** [comment]
Thank you @asomov !
