### ISSUE TITLE
Getters needed for ignored properties

### ISSUE THREAD

**Issue by maroony** [FasterXML/jackson-dataformats-text#476]
I'm wondering that I have to write getters for ignored properties. Here's an working example:

```java
import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;

@JsonPropertyOrder({
    "text",
    "ignored",
    "number"
})
@JsonIgnoreProperties(ignoreUnknown = true)
public class Example {

  private String text;
  private Integer number;

  @JsonCreator()
  public Example(String text, Integer number) {
    this.text = text;
    this.number = number;
  }

  public String getText() {
    return text;
  }

  public Integer getNumber() {
    return number;
  }

  // jackson needed getter
  public Object getIgnored() {
    return null;
  }

  public static void main(String[] args) throws IOException {

    CsvMapper csvMapper = new CsvMapper();
    csvMapper.registerModule(new ParameterNamesModule());
    CsvSchema csvSchema = csvMapper.schemaFor(Example.class);

    String value = "foo, ignoredValue, 123";

    MappingIterator<Example> iterator = csvMapper.readerFor(Example.class)
        .with(csvSchema)
        .readValues(value);

    var nextValue = iterator.next();

    System.out.println(nextValue.getText() + ", " + nextValue.getNumber());

  }
}
```

If you *delete* the getter `getIgnored()`, the following exception will be thrown:

```
Exception in thread "main" com.fasterxml.jackson.databind.RuntimeJsonMappingException: Cannot deserialize value of type `java.lang.Integer` from String "ignoredValue": not a valid `java.lang.Integer` value
 at [Source: (StringReader); line: 1, column: 5] (through reference chain: Example["number"])
        at com.fasterxml.jackson.databind.MappingIterator._handleMappingException(MappingIterator.java:416)
        at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:201)
        at Example.main(Example.java:55)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "ignoredValue": not a valid `java.lang.Integer` value
 at [Source: (StringReader); line: 1, column: 5] (through reference chain: Example["number"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1958)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1245)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:848)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:827)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:531)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:283)
        at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:199)
        ... 1 more
```

Is this expected behavior? Is there something I can do to omit writing these getters? 

Jackson-Version: 2.17.1

**Comment by maroony** [comment]
Thanks for pointing this out. Header lines are usually not usable in my case, because the CSV files are delivered from external sources. Manually building the `CsvSchema` feels like a lot of extra work for files with hundreds of columns. Looking forward to an improvement:-)

**Comment by cowtowncoder** [comment]
Also: ideas of how this could work: as things are, I am not sure how this could be made to work.

But I have to say I am also surprised by the exception as that would suggest decoder did actually know about the property mapping from column.

Test needs some tweaks to be used here (need to get rid of parameter module), but that should be doable. So the first thing we could do is add a failing test based on code included here. And yes, PRs are welcome (even just for failing test)!

**Comment by maroony** [comment]
I added a second example to my issue description where I put the `ignoredValue` to the last column. Now there is a different exception. Maybe this is also interesting for you.

**Comment by cowtowncoder** [comment]
Re-reading the description, I came to realization that this is quite tricky to support as requested: there does need to be some kind of logical property to indicate something matching column -- `@JsonIgnoreProperties` can't do that (it only lists things to ignore), although `@JsonPropertyOrder` might theoretically work.

Leaving open just in case.
